name: Build and Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies     
        run: npm install
      - name: Start Server
        run: npm run server &
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SERVER_SESSION_SECRET: ${{ secrets.SERVER_SESSION_SECRET }}
      - name: Client side unit tests
        run: npm run test
        env:
          REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}        
  deploy: ## <-- this is the new stuff
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "freego-hazard-free"
          heroku_email: "sulaimanbada8048@gmail.com"
